---
# ===========================================================================
# Install Rundeck to the rundeck servers
# Before executing the playbook, install below roles using the command 
# ansible-galaxy install robertdebock.rundeck
# ansible-galaxy install robertdebock.service
# ===========================================================================
- hosts: rundeck
  become: true
  gather_facts: yes
  roles:
  - robertdebock.bootstrap
  - robertdebock.java
  - robertdebock.service
  - robertdebock.common
  - robertdebock.rundeck