---

# ===========================================================================
#   Install eqstraining application
# ===========================================================================
- hosts: appserver1
  become: true
  tasks:
    - name: "Ensure system package cache is updated."
      apt:
        update_cache: "yes"
    - name: Install required Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-8-jdk

    - name: Copy the service file
      copy:
        src: eqstraining/eqstraining.service
        dest: /lib/systemd/system/eqstraining.service
        owner: vagrant 
        group: vagrant
        mode: 0755

    - name: "Ensure the eqs is started and starts at host boot."
      service:
        name: eqstraining
        enabled: true
        state: started
        
    - pause: seconds=60
    
    - name: "Check if eqs-team application is accessible."
      uri:
        url: http://127.0.0.1:8090/eqs-team/
        method: GET
        status_code: 200

    - name: "Check if eqs-team - employee details is accessible."
      uri:
        url: http://127.0.0.1:8090/eqs-team/employee-details.html
        method: GET
        status_code: 200

    - name: Run CRON job every minute to check the service
      cron:
        name: "eqstraining_service_check"
        user: "vagrant"
        job: "/vagrant/applications/eqstraining/servicecheck.sh >> /vagrant/applications/eqstraining/service_check.log"
        state: present
