---
# ===========================================================================
# Do setup on all hosts we want to monitor
# ===========================================================================
- hosts: rundeck  # we want the metrics of the monitoring server too
  vars:
    BLACKBOX_VERSION: '0.16.0'
    BLACKBOX_SRC_LOCATION: 'https://github.com/prometheus/blackbox_exporter/releases/download'
    BLACKBOX_SRC_FILE: "{{BLACKBOX_SRC_LOCATION}}/v{{BLACKBOX_VERSION}}/blackbox_exporter-{{BLACKBOX_VERSION}}.linux-amd64.tar.gz"
  become: true

  tasks:
    - name: "Un-archive the blackbox_exporter"
      unarchive:
        src: '{{BLACKBOX_SRC_FILE}}'
        dest: /tmp/
        remote_src: yes
     
    - name: "Create a user for blackbox_exporter"
      user:
        name: blackbox_exporter
        shell: /bin/false

    - name: "Copy the node exporter to local bin"
      copy:
        src: /tmp/blackbox_exporter-{{BLACKBOX_VERSION}}.linux-amd64/blackbox_exporter
        dest: /usr/local/bin/blackbox_exporter
        owner: blackbox_exporter 
        group: blackbox_exporter 
        mode: 0755
        remote_src: True
 
    - name: Create a directory /etc/blackbox_exporter if it does not exist
      file:
        path: /etc/blackbox_exporter
        state: directory
        mode: '0775'
        owner: blackbox_exporter
        group: blackbox_exporter

    - name: "Copy blackbox config file"
      copy: 
        src: /tmp/blackbox_exporter-{{BLACKBOX_VERSION}}.linux-amd64/blackbox.yml
        dest: /etc/blackbox_exporter/blackbox.yml
        owner: blackbox_exporter 
        group: blackbox_exporter 
        mode: 0755
        remote_src: True
           
    - name: "Create a custom service for blackbox_exporter"
      copy: 
        src: blackbox_exporter.service 
        dest: /etc/systemd/system/blackbox_exporter.service
        owner: blackbox_exporter 
        group: blackbox_exporter 
        mode: 0755
        
    - name: "Start the blackbox_exporter service"
      service:
        name: blackbox_exporter
        enabled: true
        state: started
        
    - name: "Ensure the Node Exporter is started and starts at host boot."
      service:
        name: blackbox_exporter
        enabled: true
        state: started

    - name: "Check if the service emits metrics."
      uri:
        url: http://127.0.0.1:9100/metrics
        method: GET
        status_code: 200