---

# ===========================================================================
# Prometheus server specific setup 
# ===========================================================================
- hosts: prometheus
  vars:
    PROMETHEOUS_VERSION: '2.13.1'
    PROMETHEOUS_SRC_LOCATION: 'https://github.com/prometheus/prometheus/releases/download/'
    PROMETHEOUS_SRC_FILE: "{{PROMETHEOUS_SRC_LOCATION}}/v{{PROMETHEOUS_VERSION}}/prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64.tar.gz"
  become: true
  tasks:
    # --- Prometheus --------------------------------------------------------
    - name: "Un-archive the Prometheus installer"
      unarchive:
       #src: prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64.tar.gz
       src: "{{PROMETHEOUS_SRC_FILE}}"
       dest: /tmp/ 
       remote_src: yes
        
    - name: "Create a user for Prometheus"
      user:
        name: prometheus
        shell: /bin/false
        
    - name: Create a directory  /etc/prometheus if it does not exist
      file:
        path: /etc/prometheus
        state: directory
        mode: '0775'
        owner: prometheus
        group: prometheus
        
    - name: Create a directory /var/lib/prometheus if it does not exist
      file:
        path: /var/lib/prometheus
        state: directory
        mode: '0775'
        owner: prometheus
        group: prometheus
        
    - name: Copy promtool executable to bin directory
      copy:
        src: /tmp/prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64/promtool
        dest: /usr/local/bin/
        owner: prometheus
        group: prometheus
        mode: '0775'
        remote_src: yes
        
    - name: Copy prometheus executable to bin directory
      copy:
        src: /tmp/prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64/prometheus
        dest: /usr/local/bin/
        owner: prometheus
        group: prometheus
        mode: '0775'       
        remote_src: yes
        
    - name: Copy prometheus consoles to /etc/prometheus
      copy:
        src: /tmp/prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64/consoles 
        dest: /etc/prometheus/consoles
        owner: prometheus
        group: prometheus
        mode: '0775'
        directory_mode: yes        
        remote_src: yes
        
    - name: Copy prometheus console_libraries to /etc/prometheus
      copy:
        src: /tmp/prometheus-{{PROMETHEOUS_VERSION}}.linux-amd64/console_libraries 
        dest: /etc/prometheus/console_libraries
        owner: prometheus
        group: prometheus
        mode: '0775'
        directory_mode: yes   
        remote_src: yes
        
    - name: "Create a custom service for prometheus"
      copy: 
        src: prometheus.service 
        dest: /etc/systemd/system/prometheus.service
        owner: prometheus 
        group: prometheus 
        mode: 0755
        
    - name: "Start the prometheus service"
      service:
        name: prometheus
        enabled: true
        state: started
        
    - name: "Configure the Prometheus server."
      copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus 
        group: prometheus
        mode: 0755        
      notify: event_restart_prometheus
      
    - name: "Copy Rules"
      copy:
        src: rules.yml
        dest: /etc/prometheus/rules.yml
        owner: prometheus 
        group: prometheus
        mode: 0755        
      notify: event_restart_prometheus       

    - name: "Ensure Prometheus is started and starts at host boot."
      service:
        name: prometheus
        enabled: true
        state: started
        
    - pause: seconds=10
    
    - name: "Check if Prometheus is accessible."
      uri:
        url: http://127.0.0.1:9090/graph
        method: GET
        status_code: 200

  # --- After all tasks are executed (if notified) --------------------------
  handlers:
    - name: "Restart the Prometheus service."
      service:
        name: prometheus
        state: restarted
      listen: event_restart_prometheus