alertmanager:
    global:
      slack_api_url: https://hooks.slack.com/services/*****************
    receivers:
    - name: 'alert-team'
      slack_configs:
      - channel: "#prom-alert"
        send_resolved: true
        text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

    - name: 'slack_rundeck'
      slack_configs:
        - api_url: https://hooks.slack.com/services/**************************
          channel: '#rundeck'
      webhook_configs:
      - url: 'http://rundeck:4440/api/34/webhook/3LBcTC8zd28kDpFxNiLIYxYztYu3uHgc#appserverprobe'
        text: '{ "msg":"ok" }'

    route:
      group_by: ['instance', 'severity']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10m
      receiver: 'alert-team'
      routes:
      - match:
          alertname: BlackboxProbeHttpFailure
        receiver: slack_rundeck
